language: node_js
sudo: false
node_js:
- 10
install:
- npm install
script:
- npm run build
deploy:
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    tag: dev
    on:
      branch: development
      tags: true
  - provider: npm
    email: "$NPM_EMAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      branch: master
      tags: true
